baseURL = "https://www.koenmolenaar.nl"
languageCode = "nl-nl"
title = "Koen Molenaar"
theme = "terminal"
paginate = "2"
copyright = "© Koen Molenaar 2021"
defaultContentLanguage = "nl"

[params]

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "projects"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  singlePageSite = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "K0enM"
  site = ""

[languages]
  [languages.nl]
    languageName = "Nederlands"
    title = "Koen Molenaar / Home"
    subtitle = "Koen Molenaar's Website"
    owner = "Koen Molenaar"
    keywords = ""
    copyright = "© Koen Molenaar 2021"
    menuMore = "Laat meer zien"
    readMore = "Lees meer"
    readOtherPosts = "Lees andere posts"
    missingContentMessage = "Pagina niet gevonden..."
    missingBackButtonLabel = "Terug naar de homepagina"

    [languages.nl.params.logo]
      logoText = "Koen Molenaar"
      logoHomeLink = "/"

    [languages.nl.menu]
      [[languages.nl.menu.main]]
        identifier = "about.nl"
        name = "Over"
        url = "/#about.nl"
        weight = 1

      [[languages.nl.menu.main]]
        identifier = "contact.nl"
        name = "Contact"
        url = "/#contact.nl"
        weight = 2

  [languages.en]
    languageName = "English"
    title = "Koen Molenaar / Home"
    subtitle = "Koen Molenaar's Website"
    owner = "Koen Molenaar"
    keywords = ""
    copyright = "© Koen Molenaar 2021"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Koen Molenaar"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about.en"
        name = "About"
        url = "./#about.en"
        weight = 1

      [[languages.en.menu.main]]
        identifier = "contact.en"
        name = "Contact"
        url = "./#contact.en"
        weight = 2

      
    

