baseURL = "/"
languageCode = "en-US"
title = "Koen Molenaar"
theme = "terminal"
copyright = "© Koen Molenaar 2024"
defaultContentLanguage = "en"

[params]

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "write-ups"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  singlePageSite = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.pagination]
  pagerSize = 2
  

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "K0enM"
  site = ""

[languages]
  [languages.nl]
    languageName = "Nederlands"
    title = "Koen Molenaar / Home"
    subtitle = "Koen Molenaar's Website"
    owner = "Koen Molenaar"
    keywords = ""
    copyright = "© Koen Molenaar 2025"
    menuMore = "Laat meer zien"
    readMore = "Lees meer"
    readOtherPosts = "Lees andere posts"
    missingContentMessage = "Pagina niet gevonden..."
    missingBackButtonLabel = "Terug naar de homepagina"
    contentDir = "content/nl"
    disabled = true

    [languages.nl.params.logo]
      logoText = "Koen Molenaar"
      logoHomeLink = "/"

    [languages.nl.menu]
      [[languages.nl.menu.main]]
        identifier = "about"
        name = "Over"
        url = "/nl/about"
        weight = 1

      [[languages.nl.menu.main]]
        identifier = "write-ups"
        name = "Write-ups"
        url = "/nl/write-ups"
        weight = 2
  
      [[languages.nl.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/nl/contact"
        weight = 3

  [languages.en]
    languageName = "English"
    title = "Koen Molenaar / Home"
    subtitle = "Koen Molenaar's Website"
    owner = "Koen Molenaar"
    keywords = ""
    copyright = "© Koen Molenaar 2025"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    contentDir = "content/en"
    disabled = false

    [languages.en.params.logo]
      logoText = "Koen Molenaar"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        pageRef = "/about"
        weight = 1

      [[languages.en.menu.main]]
        identifier = "write-ups"
        name = "Write-ups"
        pageRef = "/write-ups"
        weight = 2

      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        pageRef = "/contact"
        weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

